version: "3"

services:

  # client:
  #   container_name: frontend
  #   build:
  #     context: ./
  #     dockerfile: ./docker/frontend/Dockerfile
  #   ports:
  #     - 8080:8080
  #     - 8000:8000
  #   volumes:
  #     - ./frontend:/data
  #   environment:
  #     - API_URL=http://localhost:8080/
  #   command: ["npm", "run", "serve"]

  mongo:
    container_name: mongo
    build:
      context: ./
      dockerfile: ./docker/mongo/Dockerfile
    volumes:
      - ./data:/data/mongo
    ports:
      - "27017:27017"
    expose:
      - 27017

  server:
    container_name: server
    restart: always
    # command: nodemon --watch *.js
    command: nodemon --inspect=0.0.0.0:9229 app.js
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    volumes:
      # Significa que, quando as imagens forem salvas nesse caminho, dentro do container,
      # elas estarão sendo salvas, na verdade, na máquina local, no mesmo caminho.
      - ./backend:/usr/src/baixador-sentinel
      - /usr/local/data/sentinel2:/usr/local/data/sentinel2
    # container_name: node-with-gdal
    links:
      - mongo
    depends_on:
      - "mongo"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/sentinel
    ports:
      - "8123:8123"
      - "9229:9229"
